export const MAX_EDIT_ITERATIONS = 4
export const DEFAULT_ACCEPTABLE_SCORE = 95
export const MIN_ACCEPTABLE_SCORE = 75
export const DRAFT_CANDIDATE_COUNT = 3
export const DRAFT_SELECTOR_COMPLEXITY_THRESHOLD = 40
